
// console.log("Opening Settings page");
const STOPS = {
  "150DALE": "U.S. 150 and Dale",
  "150DOD": "U.S. 150 and Dodson Dr.",
  "150UNI": "U.S. 150 and University",
  "1STARY": "First and Armory",
  "1STDAN": "First and Daniel",
  "1STGRG": "First and Gregory",
  "1STGTY": "First and Gerty",
  "1STHZLWD": "First and Hazelwood",
  "1STIHOTEL": "First at iHotel",
  "1STLAKEPKN": "First and Lake Park North",
  "1STLAKEPKS": "First and Lake Park South",
  "1STSMR": "First and St. Mary's Rd.",
  "1STSPFLD": "First and Springfield",
  "1STSTDM": "First and Stadium",
  "1STWDSR": "First and Windsor",
  "2NDCHCH": "Second and Church",
  "2NDPK": "Second and Park",
  "3RDDAN": "Third and Daniel",
  "4THARY": "Fourth and Armory",
  "4THBIELFELDT": "Fourth at Bielfeldt",
  "4THBRAD": "Fourth and Bradley",
  "4THCHAL": "Fourth and Chalmers",
  "4THDAN": "Fourth and Daniel",
  "4THGRG": "Fourth and Gregory",
  "4THJOHN": "Fourth and John",
  "4THKBY": "Fourth and Kirby",
  "4THPA": "Fourth and Pennsylvania",
  "4THPDY": "Fourth and Peabody",
  "4THSMR": "Fourth and St. Mary's",
  "5THARMRY": "Fifth and Armory",
  "5THBRD": "Fifth and Beardsley",
  "5THCHAL": "Fifth and Chalmers",
  "5THCLMBA": "Fifth and Columbia",
  "5THERKA": "Fifth and Eureka",
  "5THGRV": "Fifth and Grove",
  "5THWASH": "Fifth and Washington",
  "6THARY": "Sixth and Armory",
  "6THBRAD": "Sixth and Bradley",
  "6THGRG": "Sixth and Gregory",
  "6THPDY": "Sixth and Peabody",
  "ADRSNBKWD": "Anderson and Burkwood",
  "ADRSNCO": "Anderson and Colorado",
  "ADRSNFRLN": "Anderson and Fairlawn",
  "ADRSNHRDG": "Anderson and Harding",
  "ADRSNMFRD": "Anderson and Mumford",
  "ADRSNMI": "Anderson and Michigan",
  "ADRSNSLVR": "Anderson and Silver",
  "ALDI150": "Aldi at Rt. 150",
  "ALPBRAD": "Alpine and Bradley",
  "ALPTMBLN": "Alpine and Timberline",
  "AMBMYRA": "Amber and Myra Ridge",
  "AMBPHILO": "Amber and Philo",
  "AMBUC": "University and Ambucs Park Entrance",
  "ANTAMRN": "Anthony at Ameren",
  "ANTCMBL": "Anthony and Campbell",
  "ANTDOBB": "Anthony and Dobbins",
  "ANTGOODWILL": "Anthony Dr. at Goodwill",
  "ANTHNYNAP": "Anthony at Napleton's",
  "ANTHNYWLLW": "Anthony and Willow",
  "ANTHYDUSK": "Anthony and Dusk",
  "ANTHYRK": "Anthony at Rural King",
  "ANTHYWSS": "Anthony at Woodspring Suites",
  "ANTMATS": "Anthony and Mattis",
  "ANTNSHR": "Anthony and North Shore",
  "ANTNWH": "Anthony at National Warehouse",
  "ANTWTRS": "Anthony and Walters",
  "APTHICRS": "Airport Rd. and High Cross",
  "ARC": "Activities and Recreation",
  "ARPRTCLFTN": "Airport and Clifton",
  "ARPRTCNGHM": "Airport and Cunningham",
  "ARPRTCPTVA": "Airport and Captiva",
  "ARPRTDNLD": "Airport and Donald",
  "ARPRTFDCRST": "Airport and Fieldcrest",
  "ARPRTLNDSFRM": "Airport and Landis Farm",
  "ARPRTSKYLN": "Airport and Skyline",
  "ARPRTWLLW": "Airport and Willow",
  "ARPTRDFF": "Airport Road at Farm and Fleet",
  "ARYWRT": "Armory and Wright",
  "ASHTON": "First at Ashton Woods",
  "ATRIUM": "Atrium Apts",
  "BAYBRDWLK": "Baytowne and Boardwalk",
  "BCHRMN": "Beech and Romine",
  "BDMRBLMY": "Broadmoor and Bellamy",
  "BDMRCRSNT": "Broadmoor and Crescent",
  "BDMRDVD": "Broadmoor and David",
  "BDMRGLN": "Broadmoor and Galen",
  "BDMRLCNPL": "Broadmoor and Lincoln Pl.",
  "BDMRLNWD": "Broadmoor and Lynwood",
  "BDMRLSDED": "Broadmoor and Lakeside Dr.",
  "BDMRRBT": "Broadmoor and Robert",
  "BDWYCCR": "Broadway and Country Club",
  "BDWYCM": "Broadway at Save A Lot",
  "BDWYKER": "Broadway and Kerr",
  "BDWYLST": "Broadway and Stebbins",
  "BDWYOKLN": "Broadway and Oakland",
  "BDWYPK": "Broadway and Park",
  "BDWYTPSN": "Broadway and Thompson",
  "BDWYUNI": "Broadway and University",
  "BLBOAPSPCT": "Balboa and Prospect",
  "BLDRRDGPPRML": "Boulder Ridge and Peppermill",
  "BLGRSBCAVSTA": "Bluegrass and Boca Vista",
  "BLGRSBLDRRDG": "Bluegrass and Boulder Ridge",
  "BLGRSSMRSG": "Bluegrass and Summersage",
  "BLOMAL": "Bloomington and Alabama",
  "BLOMHD": "Bloomington at Home Depot",
  "BLOMHGN": "Bloomington and Hagan",
  "BLOMHILND": "Bloomington and Highland",
  "BLOMMCNLY": "Bloomington and McKinley",
  "BLOMPNR": "Bloomington Rd. at Pioneer Plaza",
  "BLOMPSPCT": "Bloomington and Prospect",
  "BLOMSNST": "Bloomington and Sunset",
  "BLOMWLS": "Bloomington and Willis",
  "BNBLRAMY": "Bonnie Blair and Amy",
  "BNBLRGDMD": "Bonnie Blair and Gold Medal",
  "BNBLRNNBTH": "Bonnie Blair and Nancy Beth",
  "BNBLRSHRN": "Bonnie Blair and Sharon",
  "BNBLRVLR": "Bonnie Blair and Valerie",
  "BNFLDAGNS": "Brownfield and Agnes",
  "BNFLDAPT": "Brownfield and Airport Rd.",
  "BNFLDARL": "Brownfield and Arlene",
  "BNFLDCFTN": "Brownfield and Clifton",
  "BNFLDCLMBA": "Brownfield and Columbia",
  "BNFLDJHN": "Brownfield and Johnson",
  "BNFLDML": "Brownfield and Mary Lou Dr.",
  "BNFLDPKNS": "Brownfield and Perkins",
  "BNFLDPRVW": "Brownfield and Prairieview",
  "BNFLDSLYN": "Brownfield and Sharlyn",
  "BNTBRKBBCT": "Bentbrook and Bentbrook Ct",
  "BNTBRKCBLFLD": "Bentbrook and Cobblefield",
  "BNTBRKGLFCRK": "Bentbrook and Golf Creek",
  "BNTBRKPNCRST": "Bentbrook and Pinecrest",
  "BNTBRKRVRKNL": "Bentbrook and Riverknoll",
  "BNTBRKSTLY": "Bentbrook and Staley",
  "BRAD": "Bradley between Pomona and WLRW",
  "BRADCFD": "Bradley and Country Fair Drive",
  "BRADCLTN": "Bradley and Clayton",
  "BRADCMI": "Bradley and Champaign St.",
  "BRADCRVR": "Bradley and Carver",
  "BRADDNCN": "Bradley and Duncan",
  "BRADELM": "Bradley and Elm",
  "BRADHGN": "Bradley and Hagan",
  "BRADHKRY": "Bradley and Hickory",
  "BRADJAS": "Bradley and James",
  "BRADMATS": "Bradley and Mattis",
  "BRADMCNLY": "Bradley and McKinley",
  "BRADNEIL": "Bradley and Neil",
  "BRADPSPCT": "Bradley and Prospect",
  "BRADSTE": "Bradley and State",
  "BRADWLS": "Bradley and Willis",
  "BRADWMBG": "Bradley and Willliamsburg",
  "BRDNTLSN": "Bardeen and Toalson",
  "BRDWLKINT": "Boardwalk and Interstate",
  "BRDWLKMJR": "Boardwalk and Meijer Dr.",
  "BRDWLKTCB": "Boardwalk and Town Center Blvd",
  "BRDYHI": "Brady and High",
  "BRNFLDDNLD": "Brownfield and Donald",
  "BRTTRLKNTNKNL": "Brittany Trail and Kensington Knoll",
  "BRTTRLMLKN": "Brittany Trail and Mullikin",
  "BRTTRLSTHFRD": "Brittany Trail and Southford",
  "BRTTRLSTHFRDTR": "Brittany Trail and Southford Trace West",
  "BRTTRLSTLY": "Brittany Trail and Staley",
  "BRWSWDFLD": "Burwash and Woodfield",
  "BSLNGWN": "Beslin and Goodwin",
  "BTSLRMN": "Butzow and Lierman",
  "CAMPUSCIR": "Campus Circle",
  "CATFN": "Carle at the Fields North",
  "CATFS": "Carle at the Fields South",
  "CB": "Country Brook",
  "CBLFLDBDGPT": "Cobblefield and Bridge Point Dr",
  "CBLFLDCRL": "Cobblefield and Crail",
  "CBLFLDEGLWD": "Cobblefield and Englewood",
  "CBLFLDGLNBRK": "Cobblefield and Glenn Brooke",
  "CBLFLDINV": "Cobblefield and Inverness",
  "CBRTPK": "Colbert Park",
  "CCRDVSN": "Country Club and Division",
  "CCRWLLW": "Country Club and Willow",
  "CCSJ": "County Satellite Jail",
  "CE": "Central High East",
  "CENTRAL": "Central High",
  "CFDCAMP": "Country Fair Dr. and Camp",
  "CFDCONE": "Country Fair Dr. and Cone",
  "CFDFLDEV": "Country Fair Dr. at Fluid Events",
  "CFDGRMCY": "Country Fair Drive at Gramercy",
  "CFDPK": "Country Fair Dr. and Park",
  "CFDRP": "Country Fair Dr. at R.P. Lumber",
  "CFDSSI": "Country Fair Dr. at Social Security",
  "CHCH": "Church between New and Prospect",
  "CHCHBUSY": "Church and Busey",
  "CHCHDNTN": "Church and Denton",
  "CHCHDRPR": "Church and Draper",
  "CHCHELM": "Church and Elm",
  "CHCHFAIR": "Church and Fair",
  "CHCHGRFLD": "Church and Garfield",
  "CHCHJAS": "Church and James",
  "CHCHLYN": "Church and Lynn",
  "CHCHMATS": "Church and Mattis",
  "CHCHMCNLY": "Church and McKinley",
  "CHCHNEIL": "Church and Neil",
  "CHCHNEW": "Church and New",
  "CHCHORCD": "Church and Orchard",
  "CHCHPRRE": "Church and Prairie",
  "CHCHPSPCT": "Church and Prospect",
  "CHCHRSL": "Church and Russell",
  "CHCHSTE": "Church and State",
  "CHCHVCTR": "Church and Victor",
  "CHCHWLS": "Church and Willis",
  "CHEMLS": "Chemical and Life Sciences",
  "CHHLAPLWD": "Cherry Hills and Applewood",
  "CHHLCTS": "Cherry Hills and Curtis",
  "CHHLLKVW": "Cherry Hills and Lakeview",
  "CHHLPNVY": "Cherry Hills and Pine Valley",
  "CLMBABTSYRS": "Columbia and Betsy Ross",
  "CLMBAHNK": "Columbia and Hancock",
  "CLRCHCH": "Coler and Church",
  "CLRFRVW": "Coler and Fairview",
  "CLTNBLRV": "Clayton and Bellerieve",
  "CLTNCPT": "Clayton and Compton",
  "CLTNCRVCR": "Clayton and Creve Coeur",
  "CLTNDLMR": "Clayton and Delmar",
  "CLTNDNCN": "Clayton and Duncan",
  "CLTNHGN": "Clayton and Higgins",
  "CLTNHLT": "Clayton and Hilltop",
  "CLTNHV": "Clayton and High View",
  "CLTNIRVN": "Clayton and Irvine",
  "CLTNPMNA": "Clayton and Pomona",
  "CMBLCMCHE": "Campbell and Comanche",
  "CMBLCRT": "Campbell and Curt",
  "CMBLDBNS": "Campbell and Dobbins",
  "CMBLQNWAY": "Campbell and Queensway",
  "CMIHS": "Champaign House",
  "CNHMCLD": "Cunningham and Crystal Lake",
  "CNHMOKLN": "Cunningham and Oakland",
  "CNHMPK": "Cunningham and Park",
  "CNHMPKNS": "Cunningham and Perkins",
  "CNHMTPSN": "Cunningham and Thompson",
  "COLRCH": "Colorado and Larch",
  "COSL": "Colorado at Salt & Light",
  "CPRRDGBLKHK": "Copper Ridge and Blackhawk",
  "CPRRDGCPR": "Copper Ridge and Copper",
  "CPRRDGIRNWD": "Copper Ridge and Ironwood",
  "CPRRDGMLKN": "Copper Ridge and Mullikin",
  "CPRRDGSND": "Copper Ridge and Sand",
  "CPRSPTSTLWTR": "Cyprus Point and Stillwater Landing",
  "CPTVASNBL": "Captiva and Sanibel",
  "CRNDODVR": "Coronado and Dover",
  "CRNDOVTRA": "Coronado and Ventura",
  "CROL": "Carroll between Community Center and Ker",
  "CROLKER": "Carroll and Kerr",
  "CRSGTCHWK": "Crossgate and Charwick",
  "CRSGTCRSGTCT": "Crossgate and Crossgate Ct.",
  "CRSGTIRNWD": "Crossgate and Ironwood Ln",
  "CRSNTGRNDL": "Crescent and Greendale",
  "CRSNTJMS": "Crescent at Jefferson Middle School",
  "CRSNTJOHN": "Crescent and John",
  "CRSNTPKDL": "Crescent and Parkdale",
  "CRSNTRBM": "Crescent and Round Barn Manor",
  "CRSNTROD": "Crescent and Rodney",
  "CRSNTSANG": "Crescent and Sangamon",
  "CRSNTSWD": "Crescent and Southwood",
  "CRSNTWLM": "Crescent and William",
  "CRSTWDBRAD": "Crestwood and Bradley",
  "CRSTWDCLTN": "Crestwood and Clayton",
  "CRSTWDEDHFMN": "Crestwood and Edward Hoffman",
  "CRSTWDFLNC": "Crestwood and Florence",
  "CRSTWDKTLYN": "Crestwood and Katie Lynn",
  "CRSTWDLDU": "Crestwood and Ladue",
  "CRTSWNSTN": "Curtis and Wynstone",
  "CSQRCT": "Country Squire Ct.",
  "CSQRKNCH": "Country Squire and Kinch",
  "CTGRVBRITN": "Cottage Grove and Brighton",
  "CTGRVCO": "Cottage Grove and Colorado",
  "CTGRVERN": "Cottage Grove and Eastern",
  "CTGRVGNWD": "Cottage Grove and Glenwood Oaks",
  "CTGRVGRN": "Cottage Grove and Green",
  "CTGRVHRDG": "Cottage Grove and Harding",
  "CTGRVIL": "Cottage Grove and Illinois",
  "CTGRVMCHM": "Cottage Grove and Mitchem",
  "CTGRVOR": "Cottage Grove and Oregon",
  "CTGRVPA": "Cottage Grove and Penn.",
  "CTGRVWASH": "Cottage Grove and Washington",
  "CTRYBNDSPGHL": "Country Bend and Springhill",
  "CTSMDW": "Curtis and Meadow",
  "CTSMDWBRTN": "Curtis Meadow and Brighton",
  "CTSMDWFXBRGH": "Curtis Meadow and Foxborough",
  "CTSMDWSTLY": "Curtis Meadow and Staley",
  "CTSWIN": "Curtis Road at Winfield Village",
  "CUPHD": "Public Health District on Kenyon",
  "CVTRYMYNRD": "Coventry and Maynard",
  "CVTRYRXFRD": "Coventry and Roxford",
  "DART": "DART",
  "DCC": "Devonshire Center",
  "DDSNIL": "Dodson and Illinois",
  "DDSNWASH": "Dodson and Washington",
  "DEPOT": "MTD Garage",
  "DNCNBLR": "Duncan and Blair",
  "DNCNCLKRD": "Duncan and Clark",
  "DNCNCLTN": "Duncan and Clayton",
  "DNCNCRSNG": "Duncan and Crossing Ct.",
  "DNCNCSTRG": "Duncan and Crestridge",
  "DNCNLGR": "Duncan and Lager",
  "DNCNLWNDL": "Duncan and Lawndale",
  "DNCNMWW": "Duncan and Meadows West",
  "DNCNPMDW": "Duncan and Prairie Meadow",
  "DNCNRDGWD": "Duncan and Ridgewood",
  "DNCNRLACR": "Duncan and Rolling Acres",
  "DNCNSTNBK": "Duncan and Stoneybrook",
  "DNCNSWOOD": "Duncan and Southwood",
  "DNCNVLR": "Duncan and Valerie",
  "DNCNVYBK": "Duncan and Valleybrook",
  "DNCNWTRSN": "Duncan and Watterson",
  "DODSLYBK": "Dodson Dr. East and Slayback",
  "DSC": "Bradley at DSC",
  "DSCCLK": "D.S.C. on Clark",
  "DVNLSDED": "Devonshire and Lakeside Dr.",
  "DVNMYFR": "Devonshire and Mayfair",
  "DVNPCH": "Devonshire and Peach",
  "DVNSNPR": "Devonshire and Sandpiper",
  "DVRBLBOA": "Dover and Balboa",
  "E14": "Lot E-14",
  "EAST": "Eastern",
  "EASTKER": "Eastern and Kerr",
  "EMS": "Edison Middle School",
  "FAR": "Florida Ave. Residence Hall",
  "FLADAMS": "Florida and Adams",
  "FLADRSN": "Florida and Anderson",
  "FLBRDWY": "Florida and Broadway",
  "FLBRMD": "Florida and Bermuda",
  "FLBUSEY": "Florida and Busey",
  "FLCRTS": "Florida and Curtiss",
  "FLCTGRV": "Florida and Cottage Grove",
  "FLDSFRHL": "Fields South and Farhills",
  "FLDSTNHH": "Fieldstone at Horizon Hobby",
  "FLDSTNMETRI": "Fieldstone at Metritech",
  "FLFLDR": "Florida and Florida Dr.",
  "FLJASCHER": "Florida and James Cherry",
  "FLKNCH": "Florida and Kinch",
  "FLLNCLN": "Florida and Lincoln",
  "FLLNDN": "Florida and Linden",
  "FLMPL": "Florida and Maple",
  "FLOD": "Florida and Orchard",
  "FLPHILO": "Florida and Philo",
  "FLPLSNT": "Florida and Pleasant Dr.",
  "FLRACE": "Florida and Race",
  "FLSMITH": "Florida and Smith",
  "FLSUN": "Sunnycrest Mall",
  "FLTOMPAINE": "Florida at Thomas Paine",
  "FLVIN": "Florida and Vine",
  "FLWLY": "Florida and Wiley",
  "FOXCHRSTIE": "Fox at Christie Clinic",
  "FOXDVN": "Fox and Devonshire",
  "FOXKLWD": "Fox and Knollwood",
  "FOXREMAX": "Fox at Remax Real Estate",
  "FOXRSCNCE": "Fox Drive at Rosecrance",
  "FOXSTE": "Fox Drive and State",
  "FOXSURS": "Fox Drive at SURS",
  "FOXWDSR": "Fox and Windsor",
  "FRBRCERL": "Farber at CERL",
  "FRBRNWTN": "Farber and Newton",
  "FRHLSTLY": "Farhills and Staley",
  "FRLN": "Fairlawn",
  "FRLNCTGRV": "Fairlawn and Cottage Grove",
  "FRLNERN": "Fairlawn and Eastern",
  "FRLNPTN": "Fairlawn and Patton",
  "FRLYWRDG": "Farley and West Ridge",
  "FRVWBUSEY": "Fairview and Busey",
  "FRVWGWN": "Fairview and Goodwin",
  "FRVWHRVY": "Fairview and Harvey",
  "FRVWLNCLN": "Fairview and Lincoln",
  "FTHLRBT": "Foothill and Robert",
  "GC": "Ginger Creek Apts.",
  "GDWNCB": "Goodwin at Ceramics Building",
  "GDWNMRL": "Goodwin at Materials Research",
  "GHFRACE": "George Huff and Race",
  "GLNDVN": "Galen and Devonshire",
  "GLNHRTN": "Galen and Harrington",
  "GLNPLMT": "Galen and Plymouth",
  "GLNSLBY": "Galen and Salisbury",
  "GLNSSX": "Galen and Sussex",
  "GLNTDR": "Galen and Theodore",
  "GLNWDSR": "Galen and Windsor",
  "GLNWLSH": "Galen and Wilshire",
  "GLNYKSH": "Galen and Yorkshire",
  "GRD": "Butzow at Guardian West",
  "GRDBTZ": "Guardian Dr. and Butzow",
  "GRGDNR": "Gregory and Dorner",
  "GRGIKE": "Gregory at Ikenberry Commons",
  "GRGLIB": "Gregory at Library",
  "GRGMUM": "Gregory at Mumford Hall",
  "GRN1ST": "Green and First",
  "GRN2ND": "Green and Second",
  "GRN4TH": "Green and Fourth",
  "GRN6TH": "Green and Sixth",
  "GRNADRSN": "Green and Anderson",
  "GRNBRCH": "Green and Birch",
  "GRNBUSEY": "Green and Busey",
  "GRNCDR": "Green and Cedar",
  "GRNGRGST": "Green and Gregory St.",
  "GRNGWN": "Green and Goodwin",
  "GRNLCST": "Green and Locust",
  "GRNLYN": "Green and Lynn",
  "GRNMPL": "Green and Maple",
  "GRNNEIL": "Green and Neil",
  "GRNORCH": "Green and Orchard",
  "GRNRACE": "Green and Race",
  "GRNRNDLF": "Green and Randolph",
  "GRNSTE": "Green and State",
  "GRNWRT": "Green and Wright",
  "GWNCHCH": "Goodwin and Church",
  "GWNCLK": "Goodwin and Clark",
  "GWNGRG": "Goodwin and Gregory",
  "GWNMN": "Goodwin and Main",
  "GWNNV": "Goodwin and Nevada",
  "GWNPK": "Goodwin and Park",
  "HDYINN": "Holiday Inn",
  "HGNPNR": "Hagen and Pioneer",
  "HICRSALC": "Highcross and Apostalic Life Church",
  "HICRSBA": "High Cross and Bruce Acres",
  "HICRSNDLD": "High Cross and Nordland",
  "HLFXMYNRD": "Halifax and Maynard",
  "HMTNJFSN": "Hamilton and Jefferson",
  "HNKHMTN": "Hancock and Hamilton",
  "HNKLBRTY": "Hancock and Liberty",
  "HNTRCSQR": "Hunter and Country Squire",
  "HNTRLNR": "Hunter and Lanore",
  "HRDGSTP": "Harding at Steer Place",
  "HRISBLOM": "Harris and Bloomington",
  "HRISBRAD": "Harris and Bradley",
  "HRISFMS": "Harris at Franklin Middle School",
  "HRISHRVRD": "Harris and Harvard",
  "HRTGPK": "Bradley at Heritage Park",
  "HSLRNDLF": "Hessel and Randolph",
  "HZLWDOAK": "Hazelwood and Oak",
  "IETC": "Illinois Employment Training Center",
  "ILAPTS": "Independent Living",
  "ILBDWY": "Illinois and Broadway",
  "INDIGO": "The Place at 117",
  "INTERSTWW": "Interstate and Waterview Way",
  "INTFRBR": "Interstate and Farber",
  "INTNWMK": "Interstate and Newmark",
  "INTRSRCH": "Interstate and Research",
  "INTWALMART": "Interstate Dr. at Walmart",
  "INVPSTWK": "Inverness and Prestwick Pt",
  "IRNWDSTLY": "Ironwood and Staley",
  "ISR": "Illinois Street Residence Hall",
  "ISWS": "Water Survey",
  "IT": "Illinois Terminal",
  "ITMKT": "Illinois Terminal at Market St.",
  "IU": "Illini Union",
  "JFSNCLMBA": "Jefferson and Columbia",
  "JMS": "Jefferson Middle School",
  "JOHNDGWD": "John and Dogwood",
  "JOHNDNCN": "John and Duncan",
  "JOHNDRPR": "John and Draper",
  "JOHNFAIR": "John and Fair",
  "JOHNFRANK": "John and Frank",
  "JOHNGLDVW": "John and Goldenview",
  "JOHNGRFLD": "John and Garfield",
  "JOHNHLYCST": "John and Hollycrest",
  "JOHNJAS": "John and James",
  "JOHNKNWD": "John and Kenwood",
  "JOHNLYN": "John and Lynn",
  "JOHNMATS": "John and Mattis",
  "JOHNMCHLCT": "John and Mitchell Ct.",
  "JOHNMCNLY": "John and McKinley",
  "JOHNNEW": "John and New",
  "JOHNPINE": "John and Pine",
  "JOHNPRRE": "John and Prairie",
  "JOHNPSPCT": "John and Prospect",
  "JOHNRSL": "John and Russell",
  "JOHNVCTR": "John and Victor",
  "JOHNWILS": "John and Willis",
  "JPN": "Lincoln at Japan House",
  "KBYARW": "Kirby and Arrow Rd.",
  "KBYBLPK": "Kirby and Bellepark Dr.",
  "KBYCAROL": "Kirby and Carolyn",
  "KBYCBLFLD": "Kirby and Cobblefield",
  "KBYCRNDO": "Kirby and Coronado",
  "KBYCRSNT": "Kirby and Crescent",
  "KBYDNCN": "Kirby and Duncan",
  "KBYDODD": "Kirby and Dodds",
  "KBYDWSN": "Kirby and Dawson",
  "KBYGDVWW": "Kirby and Grandview Dr. W.",
  "KBYGRNCFT": "Kirby and Greencroft",
  "KBYKNWD": "Kirby and Kenwood",
  "KBYLCLNRD": "Kirby and Lincoln Rd.",
  "KBYMATS": "Kirby and Mattis",
  "KBYMYFR": "Kirby and Mayfair",
  "KBYNEIL": "Kirby and Neil",
  "KBYOAK": "Kirby and Oak",
  "KBYPRKHVN": "Kirby and Park Haven",
  "KBYRDGRD": "Kirby and Ridge Rd.",
  "KBYROSE": "Kirby and Rose Dr.",
  "KBYRSWD": "Kirby and Rosewood",
  "KBYSCTDL": "Kirby and Scottsdale",
  "KBYSRTFRD": "Kirby and Stratford",
  "KBYSTE": "Kirby and State",
  "KBYVYRD": "Kirby and Valley Rd.",
  "KBYWAVE": "Kirby and Waverly",
  "KBYWSTRN": "Kirby and Western",
  "KERCNHM": "Kerr and Cunningham",
  "KERCROL": "Kerr and Carroll",
  "KERDVSION": "Kerr and Division",
  "KERGRLDNE": "Kerr and Geraldine",
  "KERHGHLNDS": "Kerr and Highlands",
  "KNCHLH": "Kinch and Lantern Hill",
  "KNCHRAIN": "Kinch and Rainbow View",
  "KNYNESTLND": "Kenyon at Eastland Suites",
  "KNYNFEDEX": "Kenyon at Fed Ex",
  "KNYNSTKSHK": "Kenyon at Steak and Shake",
  "KPDLNVW": "Kettering and Linview",
  "KRANNERT": "Krannert Center",
  "KRBYGLNSHR": "Kirby and Glenshire",
  "LAR": "LAR",
  "LBRTYCLMBA": "Liberty and Columbia",
  "LBRTYJEF": "Liberty and Jefferson",
  "LCNSR": "St. Mathews Parking Lot and Lincolnshire",
  "LCNSRFTHL": "Lincolnshire and Foothill",
  "LGN1ST": "Logan and First",
  "LKVWWGWD": "Lakeview and Wedgewood",
  "LKVWWTGTN": "Lakeview and Worthington",
  "LNCLNANT": "Lincoln and Anthony",
  "LNCLNBRAD": "Lincoln and Bradley",
  "LNCLNCC": "Lincoln and College Ct.",
  "LNCLNCHCH": "Lincoln and Church",
  "LNCLNEADS": "Lincoln and Eads",
  "LNCLNHIL": "Lincoln and Hill",
  "LNCLNIL": "Lincoln and Illinois",
  "LNCLNKING": "Lincoln and Kettering Park",
  "LNCLNKLRNY": "Lincoln and Killarney",
  "LNCLNOR": "Lincoln and Oregon",
  "LNCLNPA": "Lincoln and Pennsylvania",
  "LNCLNPK": "Lincoln and Park",
  "LNCLNSMR": "Lincoln and St. Marys Rd",
  "LNCLNWSCR": "Lincoln and Wascher",
  "LNHSTARBR": "Lyndhurst and Arbours Drive",
  "LNHSTARBR1": "Lyndhurst and Arbours Drive South",
  "LNHSTBDFD": "Lyndhurst and Bedford",
  "LNHSTBRWS": "Lyndhurst and Burwash",
  "LNHSTEGRN": "Lyndhurst and Evergreen Circle",
  "LNHSTLNVCT": "Lyndhurst and Lyndhurst Village Court",
  "LNHSTMAGN": "Lyndhurst and Magnolia Ct.",
  "LNHSTOML": "Lyndhurst and Old Maple Lane",
  "LNHSTPKLN": "Lyndhurst and Park Lane",
  "LNVWKLRNY": "Linview and Killarney",
  "LRMNHNTR": "Lierman and Hunter",
  "LSDMYNRD": "Lakeshore Dr. and Maynard",
  "LSE": "Lincoln Square",
  "LWNDLBLPK": "Lawndale and Bellepark",
  "MATSANTA": "Mattis and Anita",
  "MATSBDMR": "Mattis and Broadmoor",
  "MATSBLOM": "Mattis and Bloomington",
  "MATSBRCH": "Mattis and Branch Rd.",
  "MATSDVN": "Mattis and Devonshire",
  "MATSGLNPK": "Mattis and Glenn Park Dr.",
  "MATSGNSQ": "Mattis and Gentry Square Ln. South",
  "MATSHRBR": "Mattis and Harbor Point",
  "MATSINT": "Mattis and Interstate",
  "MATSIVYN": "Mattis and Ivy Ct. North",
  "MATSMDWDR": "Mattis and Meadow Dr.",
  "MATSMNA": "Mattis at Mattis North Apartments",
  "MATSPRNCTN": "Mattis and Princeton",
  "MATSRBR": "Mattis and Round Barn Rd.",
  "MATSSANG": "Mattis and Sangamon",
  "MATSSHRDN": "Mattis and Sheridan",
  "MATSSMC": "Mattis and Sumac",
  "MATSSTHWD": "Mattis and Southwood",
  "MATSSTNGT": "Mattis and Stonegate Dr.",
  "MATSUSPS": "Mattis at Post Office",
  "MATSWDSR": "Mattis and Windsor",
  "MATSWLM": "Mattis and William",
  "MCNLYERKA": "McKinley and Eureka",
  "MCNLYHVAD": "McKinley and Harvard",
  "MCRTRCA": "MacArthur and California",
  "MEIJER": "Meijer Drive at Meijer",
  "MERCAPLO": "Mercury and Apollo Dr.",
  "MERCFEDEX": "Mercury at FedEx",
  "MERCGEMCT": "Mercury and Gemini Ct.",
  "MHRYADRSN": "McHenry and Anderson",
  "MHRYLYN": "McHenry and Lynn",
  "MHRYLYN1": "McHenry and Lynn St. #1",
  "MHRYLYNE": "McHenry & Lynn - East",
  "MHRYPHILO": "McHenry and Philo",
  "MHRYPND": "McHenry and Pond",
  "MIGRNRDG": "Michigan and Greenridge",
  "MIKNCH": "Michigan and Kinch",
  "MISMITH": "Michigan and Smith",
  "MJRPSPCT": "Meijer Drive and Prospect",
  "MKPLCWLB": "Market Place at Wilbur",
  "MKTBNB": "Market St behind Barnes and Noble Books",
  "MKTBRAD": "Market St. and Bradley",
  "MKTGAR": "Market St. and Garwood",
  "MKTLGN": "Market and Logan",
  "MKTMERC": "Market St. and Mercury Dr.",
  "MKTMKTV": "Market and Marketview",
  "MKTPAUL": "Market and Paul",
  "MKTPLC": "Market Place",
  "MKTPLCCD": "Market Place and Convenience Drive",
  "MKTPLCN": "Market Place North Entrance",
  "MKTPLCNMKT": "Market Place North Entrance and Market S",
  "MKTPLCS": "Market Place South",
  "MKTPLCSE": "Market Place Southeast",
  "MKTPLCW": "Market Place West",
  "MKTRPR": "Market and Roper",
  "MKTTLP": "Market and Tulip Tree",
  "MKTV": "Marketview Dr. at Marketview Center",
  "MKTVANT": "Marketview and Anthony",
  "MKTVSAMS": "Marketview at Sams",
  "MLKNCPRRG": "Mullikin and Copper Ridge",
  "MLKNCRSGT": "Mullikin and Crossgate",
  "MLKNCTSMDW": "Mullikin and Curtis Meadow",
  "MLKNDVRBRK": "Mullikin and Doverbrook",
  "MLKNIRNWD": "Mullikin and Ironwood",
  "MLKNPATH": "Mullikin at Path",
  "MLKNRMGNTN": "Mullikin and Remington Way",
  "MLKNSTNBDG": "Mullikin and Stonebridge",
  "MLKNTRSTSHR": "Mullikin and Trostshire",
  "MLKNVLA": "Mullikin and Villa",
  "MLKNWSTBRGH": "Mullikin and Westborough",
  "MN150": "Main and Rt. 150",
  "MNABD": "Main and Art Bartell Rd.",
  "MNBRDY": "Main and Brady",
  "MNCHSNT": "Main and Chestnut",
  "MNCTGRV": "Main and Cottage Grove",
  "MNDWY": "Main and Dewey",
  "MNENIS": "Main and Ennis",
  "MNFREMNT": "Main and Fremont",
  "MNGLVR": "Main and Glover",
  "MNGRV": "Main and Grove",
  "MNHTL": "Main and Hartle",
  "MNILEAS": "Main at ILEAS",
  "MNLRMN": "Main and Lierman",
  "MNLYN": "Main and Lynn",
  "MNSCWD": "Main and Scottswood",
  "MNSMITH": "Main and Smith Rd.",
  "MNUBNA": "Main and Urbana",
  "MNVIN": "Main and Vine",
  "MNWLNT": "Main and Walnut",
  "MPLPKMPLWD": "Maplepark and Maplewood",
  "MPLPKSANG": "Maplepark and Sangamon",
  "MPLPKWLM": "Maplepark and William",
  "MRANLSD": "Moraine and Lake Shore Dr",
  "MYFRBDMR": "Mayfair and Broadmoor",
  "MYFRGTOWN": "Mayfair and Georgetown",
  "MYFRLCLNSH": "Mayfair and Lincolnshire",
  "MYFRTDR": "Mayfair and Theodore",
  "MYNDCVTRY": "Maynard and Coventry",
  "MYRASLVHL": "Myra Ridge and Silver Hill",
  "MYRATRLS": "Myra Ridge and Trails",
  "NEILANT": "Neil and Anthony Dr.",
  "NEILARC": "Neil and Arcadia",
  "NEILBELL": "Neil and Bellefontaine",
  "NEILBRD": "Neil and Beardsley",
  "NEILBRWS": "Neil and Burwash",
  "NEILCD": "Market Place at Center Drive",
  "NEILCLMBA": "Neil and Columbia",
  "NEILCNTR": "Neil and Center",
  "NEILEGB": "Neil and Edgebrook",
  "NEILERKA": "Neil and Eureka",
  "NEILGAR": "Neil and Garwood",
  "NEILHIL": "Neil and Hill St.",
  "NEILHLY": "Neil and Healey",
  "NEILHSL": "Neil and Hessel",
  "NEILINTR": "Neil and Interstate",
  "NEILKNYN": "Neil and Kenyon Road",
  "NEILMKTV": "Neil and Marketview",
  "NEILMSHL": "Neil and Marshall",
  "NEILN": "Neil and North",
  "NEILSPFLD": "Neil and Springfield",
  "NEILSTDM": "Neil and Stadium",
  "NEILTCA": "Neil and Town Center Apt.",
  "NEILTWN": "Neil and Twins",
  "NEILWASH": "Neil and Washington",
  "NEILWHT": "Neil and White",
  "NEILWLGFRD": "Neil and Walingford",
  "NPLTNANTHNY": "Napleton and Anthony",
  "NRTHWDGRG": "Northwood and George",
  "NVGRGPL": "Nevada and Gregory Place",
  "NVLNCLN": "Nevada and Lincoln",
  "NWPRTLNDSFRM": "Newport and Landis Farm",
  "NWTNLGGT": "Newton and Leggett",
  "NWTNNBL": "Newton and Nobel",
  "NWTNNWMK": "Newton and Newmark",
  "OAK": "Oak between Hazelwood and St. Mary's",
  "OAKANT": "Oak and Anthony",
  "OAKGTY": "Oak and Gerty",
  "OAKKNYN": "Oak and Kenyon",
  "ODMIDN": "Orchard Downs Mid-Block North",
  "ODMIDS": "Orchard Downs Mid-Block South",
  "ODNS": "Orchard Downs North Shelter",
  "ODSS": "Orchard Downs South Shelter",
  "ONENORTH": "ONE Illinois North",
  "ONESOUTH": "ONE Illinois South",
  "PA4TH": "Pennsylvania and Fourth",
  "PA6TH": "Pennsylvania and Sixth",
  "PAADRSN": "Pennsylvania and Anderson",
  "PAAG": "Pennsylvania and Ag. Engineering",
  "PABDWY": "Pennsylvania and Broadway",
  "PACARL": "Pennsylvania and Carle",
  "PACT": "Pennsylvania Ct.",
  "PADNR": "Pennsylvania and Dorner",
  "PAGWN": "Pennsylvania and Goodwin",
  "PALAW": "Pennsylvania at Law School",
  "PAMD": "Pennsylvania and Maryland Dr.",
  "PAORCH": "Pennsylvania and Orchard",
  "PAPAR": "Pennsylvania at PAR",
  "PAR": "Pennsylvania Ave. Residence Hall",
  "PARACE": "Pennsylvania and Race",
  "PARKVIEW": "Parkview",
  "PAVIN": "Pennsylvania and Vine",
  "PAWILEY": "Pennsylvania and Wiley Dr.",
  "PBLBRKBLGRS": "Pebblebrook and Bluegrass",
  "PBLBRKRKDL": "Pebblebrook and Rockdale",
  "PDKELOTB": "Paddock Dr. East at Winfield Village Lot",
  "PDKWLOTG": "Paddock Dr. West at Winfield Village Lot",
  "PDKWLOTM": "Paddock Dr. West at Winfield Village Lot",
  "PHILOCO": "Philo and Colorado",
  "PHILOHRDG": "Philo and Harding",
  "PHILOLRL": "Philo and Laurel",
  "PHILOMFRD": "Philo and Mumford",
  "PHILOPA": "Philo and Pennsylvania",
  "PHILOSCVL": "Philo and Scovill",
  "PHILOSLVR": "Philo and Silver",
  "PHILOWDSR": "Philo and Windsor",
  "PKCNTRL": "Park and Central",
  "PKLN": "Parkland College",
  "PKLNBDFD": "Park Lane and Bedford",
  "PKLNCTBRAD": "Parkland Ct. and Bradley",
  "PKLNSTFD": "Park Lane and Stanford",
  "PKMCCLGH": "Park and McCullough",
  "PKNSCHKE": "Perkins and Cherokee",
  "PKNSCOOK": "Perkins and Cooks Lane",
  "PKNSCROL": "Perkins and Carroll",
  "PKNSEAST": "Perkins and Eastern",
  "PKNSHICRS": "Perkins and High Cross",
  "PKNSIVAN": "Perkins at Ivanhoe",
  "PKNSRICH": "Perkins and Richard",
  "PKNSRNTRW": "Perkins and Raintree Woods",
  "PKRMN": "Park and Romine",
  "PKWRT": "Park and Wright",
  "PLACYNTHA": "Paula and Cynthia",
  "PLAGH": "Paula and Garden Hills Drive",
  "PLAHNYSKL": "Paula and Honeysuckle",
  "PLAJEANNE": "Paula and Jeanne",
  "PLAJOANE": "Paula and Joanne Lane",
  "PLAKIRK": "Paula and Kirk Lane",
  "PLALRKSPR": "Paula and Larkspur",
  "PLAMATS": "Paula and Mattis",
  "PLAMCNLY": "Paula and McKinley",
  "PLAMELNE": "Paula and Melanie",
  "PLAPWRS": "Paula and Powers",
  "PLASTIPAK": "Plastipak",
  "PLAZA": "Transit Plaza",
  "PMNABRAD": "Pomona and Bradley",
  "PMNAEH": "Pomona and Ed Hoffman",
  "PMNASTANA": "Pomona and Santa Ana",
  "PNCRSTSTLY": "Pinecrest and Staley",
  "PPRMLPBLBRK": "Peppermill and Pebblebrook",
  "PSL": "Plant Sciences Lab",
  "PSPCTASRD": "Prospect and Ayrshire Dr.",
  "PSPCTBDMR": "Prospect and Broadmoor",
  "PSPCTBRD": "Prospect and Beardsley",
  "PSPCTBRN": "Prospect and Breen",
  "PSPCTDNSN": "Prospect and Dennison",
  "PSPCTDVN": "Prospect and Devonshire",
  "PSPCTERKA": "Prospect and Eureka",
  "PSPCTFLRPK": "Prospect and Floral Park",
  "PSPCTFRAN": "Prospect and Francis",
  "PSPCTFRNS": "Prospect and Francis",
  "PSPCTGALN": "Prospect and Galen",
  "PSPCTHVD": "Prospect and Harvard",
  "PSPCTINTER": "Prospect and Interstate",
  "PSPCTJOHN": "Prospect and John",
  "PSPCTKBY": "Prospect and Kirby",
  "PSPCTLNSH": "Prospect and Lincolnshire",
  "PSPCTMJR": "Prospect at Meijer's Ent.",
  "PSPCTMKTV": "Prospect and Marketview",
  "PSPCTPKLN": "Prospect and Park Lane",
  "PSPCTVIN": "Prospect and Vine",
  "PSPCTVTRA": "Prospect and Ventura",
  "PSPCTWASH": "Prospect and Washington",
  "QNWAYRLND": "Queensway and Roland",
  "RACEHLMS": "Race and Holmes",
  "RACEIA": "Race and Iowa",
  "RACEIL": "Race and Illinois",
  "RACEIN": "Race and Indiana",
  "RACEMBRK": "Race at Meadowbrook Park",
  "RACEMDW": "Race and Meadow",
  "RACEMHRY": "Race and McHenry",
  "RACEMI": "Race and Michigan",
  "RACEMN": "Race and Main",
  "RACEMTCLR": "Race and Montclair",
  "RACEMUMFRD": "Race and Mumford",
  "RACENV": "Race and Nevada",
  "RACEOR": "Race and Oregon",
  "RACESWND": "Race and Sherwin",
  "RACEUA": "Race at Stone Creek Church",
  "RACEWASH2": "Race and Washington",
  "RACEWDSR": "Race and Windsor",
  "RBRCFD": "Round Barn Road and Country Fair Dr.",
  "RE": "High Cross and Kyle",
  "RESTURBMIN": "Restoration Urban Ministries",
  "RLACRMRJ": "Rolling Acres and Marjorie",
  "RLACRVLKDR": "Rolling Acres and Valkar Dr.",
  "RLNDAZTEC": "Roland and Aztec",
  "RLNDCMCHE": "Roland and Comanche",
  "RLNDDBNS": "Roland and Dobbins",
  "RMNBRD": "Romine and Beardsley",
  "RMNEADS": "Romine and Eads",
  "RMNTRMNT": "Romine and Tremont",
  "RNDBRNRD": "Round Barn Road",
  "RNDLFAVNDL": "Randolph and Avondale",
  "RNDLFBRAD": "Randolph and Bradley",
  "RNDLFBRD": "Randolph and Beardsley",
  "RNDLFCLARK": "Randolph and Clark",
  "RNDLFCLMBA": "Randolph and Columbia",
  "RNDLFERKA": "Randolph and Eureka",
  "RNDLFHIL": "Randolph and Hill",
  "RNDLFHLY": "Randolph and Healey",
  "RNDLFSPFLD": "Randolph and Springfield",
  "RNDLFSTNAG": "Randolph and Stanage",
  "RNDLFTRMNT": "Randolph and Tremont",
  "RNDLFUNI": "Randolph and University",
  "RNDLFVIN": "Randolph and Vine",
  "RNDLFWASH": "Randolph and Washington",
  "RNDLFWHT": "Randolph and White",
  "RNDLFWLM": "Randolph and William",
  "RSRCHHZNHBY": "Research at Horizon Hobby",
  "SCWDIL": "Scottswood and Illinois",
  "SKYLNNWPRT": "Skyline and Newport",
  "SLVRCTGRV": "Silver and Cottage Grove",
  "SLVRFLCHR": "Silver and Fletcher",
  "SLVRVWTR": "Silver and Vawter",
  "SLYBKIRA": "Slayback and Ira",
  "SLYBKMG": "Slayback and McGee",
  "SLYBKSMITH": "Slayback and Smith Rd.",
  "SMITH150": "Smith Rd. and U.S. 150",
  "SMITHCRE": "Smith and Carrie",
  "SMRGRIF": "St. Mary's Road and Griffith",
  "SMRNBVW": "Smith and Rainbow View",
  "SMROAK": "St. Mary's Road and Oak",
  "SMRSGSWTCHGRS": "Summersage and Switchgrass",
  "SPFLD": "Springfield and Round Barn",
  "SPFLDBRCH": "Springfield and Birch",
  "SPFLDBSY": "Springfield and Busey",
  "SPFLDCFD": "Springfield and Country Fair Dr.",
  "SPFLDDNCN": "Springfield and Duncan",
  "SPFLDFLDSTN": "Springfield and Fieldstone",
  "SPFLDGRGST": "Springfield and Gregory St.",
  "SPFLDHVY": "Springfield and Harvey",
  "SPFLDJAS": "Springfield and James",
  "SPFLDKNWD": "Springfield and Kenwood",
  "SPFLDLYN": "Springfield and Lynn",
  "SPFLDMATS": "Springfield and Mattis",
  "SPFLDMCNLY": "Springfield and McKinley",
  "SPFLDNEW": "Springfield and New",
  "SPFLDPINE": "Springfield and Pine",
  "SPFLDPRC": "Springfield at Phillips Rec. Ctr.",
  "SPFLDPRRE": "Springfield and Prairie",
  "SPFLDPSPCT": "Springfield and Prospect",
  "SPFLDRSL": "Springfield and Russell",
  "SPFLDRYLCT": "Springfield and Royal Ct.",
  "SPFLDSTLY": "Springfield and Staley",
  "SPFLDVNDRN": "Springfield and VanDoren",
  "SPFLDWLS": "Springfield and Willis",
  "SPFLDWLWN": "Springfield and Westlawn",
  "SPRINGPLAS": "Springfield at Plastipak",
  "SSTNGLNA": "Susan Stone and Galena",
  "SSTNMOS": "Susan Stone and Moss",
  "SSTNMYRA": "Susan Stone and Myra Ridge",
  "SSTNSMT": "Susan Stone and Summit",
  "SSXOKMNT": "Sussex and Oakmont",
  "SSXSFLD": "Sussex and Southfield",
  "SSXWIND": "Sussex and Windward",
  "SSXWTRFD": "Sussex and Waterford",
  "STDMOAK": "Stadium and Oak",
  "STEAVNDL": "State and Avondale",
  "STEBRCH": "State and Birch",
  "STEBRD": "State and Beardsley",
  "STECLARK": "State and Clark",
  "STECLMBA": "State and Columbia",
  "STEHIL": "State and Hill",
  "STEHLY": "State and Healey",
  "STEHSL": "State and Hessel Blvd.",
  "STEJOHN": "State and John",
  "STEPK": "State and Park",
  "STESPFLD": "State and Springfield",
  "STESTNAG": "State and Stanage",
  "STETC": "State and Trade Center Dr.",
  "STETRMNT": "State and Tremont",
  "STEUNI": "State and University",
  "STEVIN": "State and Vine",
  "STEWASH": "State and Washington",
  "STEWHT": "State and White",
  "STEWLM": "State and William",
  "STLYAMHT": "Staley and Amherst",
  "STLYCLBHS": "Staley and Clubhouse",
  "STLYCPRRDG": "Staley and Copper Ridge",
  "STLYINV": "Staley and Inverness",
  "STLYKBY": "Staley and Kirby",
  "STLYTRNBRY": "Staley and Turnberry",
  "STMARYSIHTL": "St. Mary's Road at iHotel",
  "STMAT": "St. Mathews",
  "STNCRKBN": "Stone Creek and Bohn",
  "STNCRKSTLWTR": "Stone Creek and Stillwater Landing",
  "STNCRKVNTRI": "Stone Creek and Venturi",
  "STP": "Colorado at Steer Place",
  "SUNNYCREST": "Sunnycrest Shopping Center",
  "SWALMART": "Savoy Walmart",
  "SWNDPNDR": "Sherwin and Pond Ridge",
  "SWNDPSMN": "Sherwin and Persimmon",
  "SWNDSWNC": "Sherwin and Sherwin Cir.",
  "SWNDSWNC2": "Sherwin and Sherwin Cir 2",
  "SWNDYNKR": "Sherwin and Yankee Ridge",
  "SWTCHGRSTRLWY": "Switchgrass and Trailway",
  "SWTCHGRSWLDFLWR": "Switchgrass and Wildflower",
  "TAT130": "Tatman and Rt. 130",
  "TCA": "Town and Country Apts.",
  "TCBMJR": "Town Center at Meijer",
  "TCBMNRDS": "Town Center and Menards",
  "TCBMRLND": "Town Center and Moreland",
  "TCBNEIL": "Town Center Blvd and Neil",
  "TCBTGT": "Town Center Blvd at Target",
  "TLSNINTER": "Toalson and Interstate",
  "TMGTCHHL": "Timbergate and Cherry Hills",
  "TMPSNPK": "Bradley and Thompson Park",
  "TRLSBRN": "Trails and Baronry",
  "TRLSCHAT": "Trails and Chatham",
  "TRLSPHILO": "Trails and Philo",
  "UHS": "Urbana High School",
  "UICU": "U of I Credit Union",
  "UMS": "Urbana Middle School",
  "UNI2ND": "University and Second",
  "UNI4TH": "University and Fourth",
  "UNI6TH": "University and Sixth",
  "UNICENT": "University and Central",
  "UNICTGRV": "University and Cottage Grove",
  "UNIDRPR": "University and Draper",
  "UNIELM": "University and Elm",
  "UNIFAIR": "University and Fair",
  "UNIGWN": "University and Goodwin",
  "UNIHKRY": "University and Hickory",
  "UNIHVY": "University and Harvey",
  "UNIJAS": "University and James",
  "UNILRMN": "University and Lierman",
  "UNILYN": "University and Lynn",
  "UNIMCLGH": "University and McCullough",
  "UNIMCNLY": "University and McKinley",
  "UNIMPL": "University and Maple",
  "UNINEIL": "University and Neil",
  "UNINEW": "University and New",
  "UNIPRRE": "University and Prairie",
  "UNIPSPCT": "University and Prospect",
  "UNIRACE": "University and Race",
  "UNIRNDLF": "University and Randolph",
  "UNIRSL": "University and Russell",
  "UNISCMR": "University and Sycamore",
  "UNIVCTR": "University and Victor",
  "UNIVIN": "University and Vine",
  "UNIWLS": "University and Willis",
  "UNIWRT": "University and Wright",
  "URBMEIJ": "Urbana Meijer",
  "UWALMART": "Urbana Walmart",
  "VETMED": "Vet-Med",
  "VINBKWD": "Vine and Burkwood Ct. W.",
  "VINCO": "Vine and Colorado",
  "VINELM": "Vine and Elm",
  "VINEMI": "Vine and Michigan",
  "VINFRLN": "Vine and Fairlawn",
  "VINGHF": "Vine and George Huff",
  "VINGRN": "Vine and Green",
  "VINHLMS": "Vine and Holmes",
  "VINHRIS": "Vine and Harris",
  "VINIL": "Vine and Illinois",
  "VINMCNLY": "Vine and McKinley",
  "VINMFRD": "Vine and Mumford",
  "VINMHRY": "Vine and McHenry",
  "VINOR": "Vine and Oregon",
  "VINSCVL": "Vine and Scovill",
  "VINWASH": "Vine and Washington",
  "VINWLS": "Vine and Willis",
  "VINWTR": "Vine and Water",
  "VKINGN": "Viking North",
  "VKINGS": "Viking South",
  "VLRALPN": "Valerie and Alpine",
  "VLRMGHN": "Valerie and Meaghan",
  "VNCENPLTN": "Vance and Napleton",
  "VTKNCH": "Vermont and Kinch",
  "WALMART": "Champaign Walmart",
  "WASH2ND": "Washington and Second",
  "WASH3RD": "Washington and Third",
  "WASH4TH": "Washington and Fourth",
  "WASHBDWY": "Washington and Broadway",
  "WASHCSQR": "Washington and Country Squire",
  "WASHKNCH": "Washington and Kinch",
  "WASHLNR": "Washington and Lanore",
  "WASHLRMN": "Washington and Lierman",
  "WASHMCRTR": "Washington and MacArthur",
  "WASHPHLPS": "Washington and Phillips",
  "WASHRAIN": "Washington and Rainbow View",
  "WASHSCWD": "Washington and Scottswood",
  "WASHSMITH": "Washington and Smith",
  "WASHTIM": "Washington and Timothy Tr.",
  "WDFLDABT": "Woodfield and Arbour Town Place",
  "WDFLDCTS": "Woodfield and Curtis Road",
  "WDGWDTMGT": "Wedgewood and Timbergate",
  "WDSR": "Windsor Rd",
  "WDSRBA": "Windsor and Bel-Aire",
  "WDSRBKSR": "Windsor and Brookshire",
  "WDSRBLDR": "Windsor and Boulder",
  "WDSRCCS": "Windsor at Christie Clinic",
  "WDSRCHHL": "Windsor and Cherry Hills",
  "WDSRCLSL": "WIndsor and Carlisle",
  "WDSRCLV": "Windsor at Clark Lindsey Village",
  "WDSRDNCN": "Windsor and Duncan",
  "WDSRFNY": "Windsor and Phinney",
  "WDSRFRMNGTN": "Windsor and Farmington",
  "WDSRJDN": "Windsor and Jordan",
  "WDSRLKWD": "Windsor and Lakewood",
  "WDSRLYN": "Windsor and Lynn",
  "WDSRMLRS": "Windsor and Melrose",
  "WDSRMYPK": "Windsor and Morrissey Park Dr.",
  "WDSRMYRA": "Windsor and Myra Ridge",
  "WDSRPSPCT": "Windsor and Prospect",
  "WDSRSCTDL": "Windsor and Scottsdale",
  "WDSRSTLW": "Windsor and Stillwater",
  "WDSRVIN": "Windsor and Vine",
  "WDSRVLGGRN": "Windsor and Village Green",
  "WDSRVYBK": "Windsor and Valleybrook",
  "WDSRWEST": "Windsor West Apts",
  "WDSRWIND": "Windsor and Windward Blvd.",
  "WDSRWNCH": "Windsor and Winchester",
  "WESTGATE": "Westgate Apts.",
  "WHITESTR": "White Street Mid-Block",
  "WHT1ST": "White and First",
  "WHT2ND": "White and Second",
  "WHTWRT": "White and Wright",
  "WILLOWBKR": "Willow and Baker",
  "WILLOWKNYN": "Willow and Kenyon",
  "WINDATMWD": "Windward and Autumnwood",
  "WINDCNTYSD": "Windward and Countryside",
  "WINDPT": "Windward Point",
  "WINDWTRFD": "Windward and Waterford",
  "WLDFLRTRLWY": "Wildflower and Trailway",
  "WLLWBESN": "Willow and Beason",
  "WLMBRNTWD": "William and Brentwood",
  "WLMCENT": "William and Centennial",
  "WLMDNCN": "William and Duncan",
  "WLMGLDVW": "William and Goldenview",
  "WLMKNWD": "William and Kenwood",
  "WLMOKCRST": "William and Oakcrest",
  "WLNTCLMBA": "Walnut and Columbia",
  "WLNTLGN": "Walnut and Logan",
  "WLNTUNI": "Walnut and University",
  "WLNTWASH": "Walnut and Washington",
  "WLRW": "Bradley at WLRW",
  "WMBGGH": "Williamsburg and Garden Hills Lane",
  "WMBGSMLN": "Williamsburg and Summerlin",
  "WMBGSTRG": "Williamsburg and Summit Ridge",
  "WNCHBKHVN": "Winchester and Brookhaven",
  "WNCHBKTRN": "Winchester and Blackthorn",
  "WNCHBRBY": "Winchester and Barberry",
  "WNCHBRCH": "Winchester and Branch",
  "WNCHSMC": "Winchester and Sumac",
  "WNCHSMR": "Winchester and Southmoor",
  "WNDSRFLDS": "Windsor and Fields South",
  "WNDSRLHRST": "Windsor and Lyndhurst",
  "WNDSRSTLY": "Windsor and Staley",
  "WNDVRCTRYBND": "Wendover and Country Bend",
  "WNDVRSMRVW": "Wendover and Summerview",
  "WNDVRWDSPG": "Wendover and Woodspring",
  "WRDKER": "Ward and Kerr",
  "WRTBCH": "Wright and Beech",
  "WRTBSLN": "Wright and Beslin",
  "WRTCHAL": "Wright and Chalmers",
  "WRTCHCH": "Wright and Church",
  "WRTHLY": "Wright and Healey",
  "WRTSTOTN": "Wright and Stoughton",
  "WRTWASH": "Wright and Washington",
  "WSFLDCRLTN": "Westfield and Carrelton",
  "WSFLDLWNDL": "Westfield and Lawndale",
  "WSFLDSANG": "Westfield and Sangamon",
  "WSFLDSRDN": "Westfield and Sheridan",
  "WSFLDWLM": "Westfield and William",
  "YMCA": "Stephens Family YMCA"
};
let autoValues = [];
for (let key in STOPS) {
  autoValues.push( {
    "name": STOPS[key],
    "value": { code: key }
  } );
}

function mySettings(props) {
  return (
    <Page>
      <Section
        title={<Text bold align="center">Favorite Bus Stops</Text>}>
        <AdditiveList
          title="Select your favorite stops"
          settingsKey="favorite_stop_setting"
          maxItems="9"
          addAction={
            <TextInput
              title="Add a bus stop"
              label="Name"
              placeholder="Type something"
              action="Add Stop"
              onAutocomplete={(value) => {
                return autoValues.filter((option) =>
                  option.name.toLowerCase().startsWith(value.toLowerCase()));
              }}
            />
          }
        />
      </Section>
    </Page>
  );
}

registerSettingsPage(mySettings);